name: Vanto
description: Aplicația Vanto pentru Android!
version: 5.0.9+2020051800

environment:
  sdk: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+2
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+2
  firebase_storage: ^3.1.3
  cloud_firestore: ^0.13.4+1
  url_launcher: ^5.4.5
  google_nav_bar: ^2.2.0
  flutter_vector_icons: ^0.2.1
  share: ^0.6.4+1
  device_info: ^0.4.2+4
  image_picker: ^0.6.6+1
  image_cropper: ^1.2.2
  webview_flutter: ^0.3.21
  flutter_downloader: ^1.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter:
   uses-material-design: true