name: Vanto
description: Aplicația Vanto pentru Android!
version: 6.0.0+2020060501

environment:
  sdk: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+2
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+2
  firebase_storage: ^3.1.3
  cloud_firestore: ^0.13.4+1
  url_launcher: ^5.4.5
  google_nav_bar: ^2.2.0
  flutter_vector_icons: ^0.2.1
  share: ^0.6.4+1
  device_info: ^0.4.2+4
  image_picker: ^0.6.6+1
  image_cropper: ^1.2.2
  shimmer: ^1.1.1

dev_dependencies:
  flappy_translator: 
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Text-Black.otf
        - asset: fonts/SF-Pro-Text-Bold.otf
        - asset: fonts/SF-Pro-Text-Semibold.otf
        - asset: fonts/SF-Pro-Text-BoldItalic.otf
        - asset: fonts/SF-Pro-Text-Heavy.otf
        - asset: fonts/SF-Pro-Text-Light.otf
        - asset: fonts/SF-Pro-Text-LightItalic.otf
        - asset: fonts/SF-Pro-Text-Medium.otf
        - asset: fonts/SF-Pro-Text-MediumItalic.otf
        - asset: fonts/SF-Pro-Text-Regular.otf
        - asset: fonts/SF-Pro-Text-RegularItalic.otf
        - asset: fonts/SF-Pro-Text-Thin.otf
        - asset: fonts/SF-Pro-Text-ThinItalic.otf

flappy_translator:
  input_file_path: "assets/local/locale.csv"
  output_dir: "lib"
  file_name: "locale"
  class_name: "Translation"
  delimiter: ";"
  start_index: 1
  depend_on_context: true
  use_single_quotes: false
  replace_no_break_spaces: false