import 'dart:async';

import 'package:flutter/material.dart';

/// This class is generated by the flappy_translator package
/// Please do not change anything manually in this file, instead re-generate it when changes are available
class Translation {
  String get homeWelcome => _getText("homeWelcome");

  String get navigationStore => _getText("navigationStore");

  String get storeCategoryGame => _getText("storeCategoryGame");

  String get storeCategoryMovie => _getText("storeCategoryMovie");

  String get storeCategorySeries => _getText("storeCategorySeries");

  String get storeCategoryExclusive => _getText("storeCategoryExclusive");

  String get storeObtain => _getText("storeObtain");

  String get navigationBack => _getText("navigationBack");

  String get navigationNext => _getText("navigationNext");

  String get navigationDone => _getText("navigationDone");

  String get navigationSettings => _getText("navigationSettings");

  String get hermesHint => _getText("hermesHint");

  String get settingsAppearance => _getText("settingsAppearance");

  String get settingsAppearanceLight => _getText("settingsAppearanceLight");

  String get settingsAppearanceDark => _getText("settingsAppearanceDark");

  String get settingsGeneral => _getText("settingsGeneral");

  String get settingsGeneralInfo => _getText("settingsGeneralInfo");

  String get settingsGeneralUpdates => _getText("settingsGeneralUpdates");

  String get settingsNotifications => _getText("settingsNotifications");

  String get hermesProfileDetails => _getText("hermesProfileDetails");

  String get hermesSecurity => _getText("hermesSecurity");

  String get hermesLogout => _getText("hermesLogout");

  String get hermesLogin => _getText("hermesLogin");

  String get hermesNoAccount => _getText("hermesNoAccount");

  String get hermesYesAccount => _getText("hermesYesAccount");

  String get generalError => _getText("generalError");

  String get generalEmail => _getText("generalEmail");

  String get generalPassword => _getText("generalPassword");

  String get generalName => _getText("generalName");

  String get setupNameTitle => _getText("setupNameTitle");

  String get setupNameSubtitle => _getText("setupNameSubtitle");

  String get generalApply => _getText("generalApply");

  String get setupProfilePhotoTitle => _getText("setupProfilePhotoTitle");

  String get setupProfilePhotoSubtitle => _getText("setupProfilePhotoSubtitle");

  String get setupProfilePhotoButton => _getText("setupProfilePhotoButton");

  String get setupProfilePhotoEdit => _getText("setupProfilePhotoEdit");

  String get hermesReAuthTitle => _getText("hermesReAuthTitle");

  String get hermesReAuthSubtitle => _getText("hermesReAuthSubtitle");

  String get hermesChangeEmailTitle => _getText("hermesChangeEmailTitle");

  String get hermesChangeEmailSubtitle => _getText("hermesChangeEmailSubtitle");

  String get hermesChangePasswordTitle => _getText("hermesChangePasswordTitle");

  String get hermesChangePasswordSubtitle =>
      _getText("hermesChangePasswordSubtitle");

  String get hermesDestroyTitle => _getText("hermesDestroyTitle");

  String get hermesDestroySubtitle => _getText("hermesDestroySubtitle");

  String get hermesDestroyButton => _getText("hermesDestroyButton");

  String get generalProfilePhoto => _getText("generalProfilePhoto");

  String get hermesChangePhotoTitle => _getText("hermesChangePhotoTitle");

  String get hermesChangePhotoSubtitle => _getText("hermesChangePhotoSubtitle");

  String get navigationHome => _getText("navigationHome");

  String get generalBalance => _getText("generalBalance");

  String get storeApps => _getText("storeApps");

  String get storeGames => _getText("storeGames");

  String get storeMovies => _getText("storeMovies");

  String get storeExclusive => _getText("storeExclusive");

  String get infoName => _getText("infoName");

  String get infoVersion => _getText("infoVersion");

  String get infoCode => _getText("infoCode");

  String get infoPackage => _getText("infoPackage");

  String get infoDevice => _getText("infoDevice");

  String get updateNotice => _getText("updateNotice");

  String get errorBadTyping => _getText("errorBadTyping");

  String get generalRetry => _getText("generalRetry");

  String get storeSheetTitle => _getText("storeSheetTitle");

  String get storeSheetSubtitle => _getText("storeSheetSubtitle");

  String get generalReport => _getText("generalReport");

  String get generalCancel => _getText("generalCancel");

  String get generalPreview => _getText("generalPreview");

  String get hermesCreateAccount => _getText("hermesCreateAccount");

  String get errorMaintenanceTitle => _getText("errorMaintenanceTitle");

  String get errorMaintenanceSubtitle => _getText("errorMaintenanceSubtitle");

  String get errorBannedTitle => _getText("errorBannedTitle");

  String get errorBannedSubtitle => _getText("errorBannedSubtitle");

  String get errorBannedAppeal => _getText("errorBannedAppeal");

  static Map<String, String> _localizedValues;

  static Map<String, String> _enValues = {
    "homeWelcome": "Hi",
    "navigationStore": "Store",
    "storeCategoryGame": "Game",
    "storeCategoryMovie": "Movie",
    "storeCategorySeries": "Series",
    "storeCategoryExclusive": "Exclusive",
    "storeObtain": "Obtain",
    "navigationBack": "Back",
    "navigationNext": "Next",
    "navigationDone": "Done",
    "navigationSettings": "Settings",
    "hermesHint": "Hermes account settings",
    "settingsAppearance": "Appearance",
    "settingsAppearanceLight": "Light",
    "settingsAppearanceDark": "Dark",
    "settingsGeneral": "General",
    "settingsGeneralInfo": "Information",
    "settingsGeneralUpdates": "Updates",
    "settingsNotifications": "Notifications",
    "hermesProfileDetails": "Profile Details",
    "hermesSecurity": "Password and Security",
    "hermesLogout": "Logout",
    "hermesLogin": "Login",
    "hermesNoAccount": "Don't have an account? Create one!",
    "hermesYesAccount": "Have an account already? Login!",
    "generalError": "Error",
    "generalEmail": "Email",
    "generalPassword": "Password",
    "generalName": "Name",
    "setupNameTitle": "What's your name?",
    "setupNameSubtitle": "This will personalize your account later.",
    "generalApply": "Apply",
    "setupProfilePhotoTitle": "Show us how beautiful you are!",
    "setupProfilePhotoSubtitle": "Upload a profile picture to suit your needs!",
    "setupProfilePhotoButton": "Choose image",
    "setupProfilePhotoEdit": "Edit image",
    "hermesReAuthTitle": "Enter your password",
    "hermesReAuthSubtitle":
        "For authorizing this settings, please re-enter your password!",
    "hermesChangeEmailTitle": "Change email",
    "hermesChangeEmailSubtitle":
        "Enter a valid email, you can reset your password if you forgot with it.",
    "hermesChangePasswordTitle": "Choose a new password",
    "hermesChangePasswordSubtitle":
        "Your password needs to have minimum 6 characters!",
    "hermesDestroyTitle": "Delete account",
    "hermesDestroySubtitle":
        "Are you sure you want to delete your accont? This action is irreversible!",
    "hermesDestroyButton": "DELETE ACCOUNT",
    "generalProfilePhoto": "Profile Photo",
    "hermesChangePhotoTitle": "Select a picture",
    "hermesChangePhotoSubtitle": "This photo will be your profile picture.",
    "navigationHome": "Home",
    "generalBalance": "Balance",
    "storeApps": "Apps",
    "storeGames": "Games",
    "storeMovies": "Movies",
    "storeExclusive": "Exclusive",
    "infoName": "Name",
    "infoVersion": "Version",
    "infoCode": "Code",
    "infoPackage": "Package",
    "infoDevice": "Device",
    "updateNotice": "Check for updates in Google Play",
    "errorBadTyping": "Check typo",
    "generalRetry": "Retry",
    "storeSheetTitle": "- Options",
    "storeSheetSubtitle": "Choose an option from the ones below",
    "generalReport": "Report a problem",
    "generalCancel": "Cancel",
    "generalPreview": "Preview",
    "hermesCreateAccount": "Create account",
    "errorMaintenanceTitle": "Maintenance break!",
    "errorMaintenanceSubtitle":
        "The servers are under maintenance. Please try again later!",
    "errorBannedTitle": "You have been banned!",
    "errorBannedSubtitle":
        "Your account has been permanently banned! In case you think this is a mistake, use the appeal button.",
    "errorBannedAppeal": "Appeal",
  };

  static Map<String, String> _roValues = {
    "homeWelcome": "Bună",
    "navigationStore": "Magazin",
    "storeCategoryGame": "Joc",
    "storeCategoryMovie": "Film",
    "storeCategorySeries": "Serial",
    "storeCategoryExclusive": "Exclusiv",
    "storeObtain": "Obține",
    "navigationBack": "Înapoi",
    "navigationNext": "Înainte",
    "navigationDone": "Gata",
    "navigationSettings": "Configurări",
    "hermesHint": "Setările contului Hermes",
    "settingsAppearance": "Aparență",
    "settingsAppearanceLight": "Luminos",
    "settingsAppearanceDark": "Întunecat",
    "settingsGeneral": "General",
    "settingsGeneralInfo": "Informații",
    "settingsGeneralUpdates": "Actualizări",
    "settingsNotifications": "Notificări",
    "hermesProfileDetails": "Detalii Profil",
    "hermesSecurity": "Parolă și Securitate",
    "hermesLogout": "Deconectare",
    "hermesLogin": "Autentificare",
    "hermesNoAccount": "Nu ai cont? Crează unul!",
    "hermesYesAccount": "Ai cont deja? Conectează-te!",
    "generalError": "Eroare",
    "generalEmail": "Email",
    "generalPassword": "Parolă",
    "generalName": "Nume",
    "setupNameTitle": "Cum te numești?",
    "setupNameSubtitle": "Acesta îți va personaliza contul mai târziu!",
    "generalApply": "Aplică",
    "setupProfilePhotoTitle": "Arată-ne cât ești de frumos!",
    "setupProfilePhotoSubtitle":
        "Încarcă o imagine de profil pentru a se potrivi nevoilor tale!",
    "setupProfilePhotoButton": "Alege imagine",
    "setupProfilePhotoEdit": "Editare imagine",
    "hermesReAuthTitle": "Reintroduceți parola",
    "hermesReAuthSubtitle":
        "Pentru a autoriza această setare, vă rugăm reintroduceți-vă parola!",
    "hermesChangeEmailTitle": "Schimbă emailul",
    "hermesChangeEmailSubtitle":
        "Introdu un email valid, veți putea reseta parola în caz că nu o știți cu ajutorul acestuia!",
    "hermesChangePasswordTitle": "Creați o parolă nouă",
    "hermesChangePasswordSubtitle":
        "Parola dumneavoastră trebuie să aibă minimum 6 caractere!",
    "hermesDestroyTitle": "Șterge contul",
    "hermesDestroySubtitle":
        "Ești sigur că dorești sa îți ștergi contul? Această acțiune este ireversibilă!",
    "hermesDestroyButton": "ȘTERGE CONTUL",
    "generalProfilePhoto": "Fotografie de Profil",
    "hermesChangePhotoTitle": "Selectează o imagine",
    "hermesChangePhotoSubtitle": "Această fotografie va fi imaginea de profil.",
    "navigationHome": "Acasă",
    "generalBalance": "Balanță",
    "storeApps": "Aplicații",
    "storeGames": "Jocuri",
    "storeMovies": "Filme",
    "storeExclusive": "Exclusiv",
    "infoName": "Nume",
    "infoVersion": "Versiune",
    "infoCode": "Cod",
    "infoPackage": "Pachet",
    "infoDevice": "Dispozitiv",
    "updateNotice": "Căutați actualizări în Google Play",
    "errorBadTyping": "Greșeală de scriere",
    "generalRetry": "Reîncearcă",
    "storeSheetTitle": "- Opțiuni",
    "storeSheetSubtitle": "Alegeți o opțiune din cele de mai jos",
    "generalReport": "Raportează o problemă",
    "generalCancel": "Anulează",
    "generalPreview": "Previzualizare",
    "hermesCreateAccount": "Creează cont",
    "errorMaintenanceTitle": "Mentenanță în curs!",
    "errorMaintenanceSubtitle":
        "Serverele sunt sub mentenanță. Vă rugăm să încercați mai târziu!",
    "errorBannedTitle": "Ai fost banat!",
    "errorBannedSubtitle":
        "Contul tău a fost banat permanent. În cazul în care crezi că e o greșeală, apasă butonul contestă.",
    "errorBannedAppeal": "Contestă",
  };

  static Map<String, String> _deValues = {
    "homeWelcome": "Hallo",
    "navigationStore": "Markt",
    "storeCategoryGame": "Spiele",
    "storeCategoryMovie": "Filme",
    "storeCategorySeries": "Serie",
    "storeCategoryExclusive": "Exklusive",
    "storeObtain": "Laden",
    "navigationBack": "Zurück",
    "navigationNext": "Weiter",
    "navigationDone": "Fertig",
    "navigationSettings": "Einstellungen",
    "hermesHint": "Konto-Einstellungen",
    "settingsAppearance": "Aussehen",
    "settingsAppearanceLight": "Hell",
    "settingsAppearanceDark": "Dunkel",
    "settingsGeneral": "Allgemein",
    "settingsGeneralInfo": "Info",
    "settingsGeneralUpdates": "Aktualisierungen",
    "settingsNotifications": "Mitteilungen",
    "hermesProfileDetails": "Profil Info",
    "hermesSecurity": "Passwort & Privatsphäre ",
    "hermesLogout": "Ausloggen",
    "hermesLogin": "Einloggen",
    "hermesNoAccount": "Hast du kein Account? Erstelle jetzt eins!",
    "hermesYesAccount": "Hast du schon ein Account? Logge dich ein!",
    "generalError": "Fehler",
    "generalEmail": "Email",
    "generalPassword": "Passwort",
    "generalName": "Name",
    "setupNameTitle": "Wie ist dein Name?",
    "setupNameSubtitle": "Das wird dein Konto später bearbeiten!",
    "generalApply": "Wählen",
    "setupProfilePhotoTitle":
        "Zeige uns wie schön du bist und wähle dein Profilbild!",
    "setupProfilePhotoSubtitle":
        "Probiere ein Profilbild um dein Account schöner zu gestalten!",
    "setupProfilePhotoButton": "Profilbild auswählen",
    "setupProfilePhotoEdit": "Profilbild bearbeiten",
    "hermesReAuthTitle": "Passwort nochmal eingeben",
    "hermesReAuthSubtitle":
        "Um diese Einstellung zu bestätigen, bitte geben Sie Ihr Passwort nochmal ein!",
    "hermesChangeEmailTitle": "Email wechseln",
    "hermesChangeEmailSubtitle":
        "Geben Sie eine gültige E-Mail Adresse ein. Sie werden es brauchen falls Sie ihr Passwort vergessen!",
    "hermesChangePasswordTitle": "Passwort wechseln",
    "hermesChangePasswordSubtitle":
        "Ihr Passwort muss mindestens 6 Buchstaben haben!",
    "hermesDestroyTitle": "Account löschen",
    "hermesDestroySubtitle":
        "Sind Sie sicher dass Sie Ihren Account löschen möchten? Sie können das dann nicht mehr abbrechen.",
    "hermesDestroyButton": "ACCOUNT LÖSCHEN",
    "generalProfilePhoto": "Profilbild",
    "hermesChangePhotoTitle": "Foto auswählen",
    "hermesChangePhotoSubtitle": "Dieses Foto wird dein Profilbild sein.",
    "navigationHome": "Startseite",
    "generalBalance": "Münzen",
    "storeApps": "Apps",
    "storeGames": "Spiele",
    "storeMovies": "Filme",
    "storeExclusive": "Exklusive Apps",
    "infoName": "Name",
    "infoVersion": "Version",
    "infoCode": "Code",
    "infoPackage": "Packung",
    "infoDevice": "Gerät",
    "updateNotice": "Suchen nach Updates in Google Play",
    "errorBadTyping": "Rechtshreibfehler überprüfen",
    "generalRetry": "Nochmal versuchen",
    "storeSheetTitle": "Optionen",
    "storeSheetSubtitle":
        "- Wählen Sie eine Option von der runter-aufgezählten",
    "generalReport": "Ein Fehler melden",
    "generalCancel": "Abbrechen",
    "generalPreview": "Vorschau",
    "hermesCreateAccount": "Erstelle ein Konto",
    "errorMaintenanceTitle": "Wartungsarbeiten",
    "errorMaintenanceSubtitle":
        "Die Server werden derzeit gewartet. Bitte versuche es später erneut.",
    "errorBannedTitle": "Vom Spiel gebannt!",
    "errorBannedSubtitle":
        "Your account has been permanently banned! In case you think this is a mistake, use the appeal button.",
    "errorBannedAppeal": "Anzeige",
  };

  static Map<String, Map<String, String>> _allValues = {
    "en": _enValues,
    "ro": _roValues,
    "de": _deValues,
  };

  Translation(Locale locale) {
    this._locale = locale;
    _localizedValues = null;
  }

  Locale _locale;

  static Translation of(BuildContext context) {
    return Localizations.of<Translation>(context, Translation);
  }

  String _getText(String key) {
    return _localizedValues[key] ?? '** $key not found';
  }

  Locale get currentLocale => _locale;

  String get currentLanguage => _locale.languageCode;

  static Future<Translation> load(Locale locale) async {
    final translations = Translation(locale);
    _localizedValues = _allValues[locale.toString()];
    return translations;
  }
}

class TranslationDelegate extends LocalizationsDelegate<Translation> {
  const TranslationDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
    Locale('ro'),
    Locale('de'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<Translation> load(Locale locale) => Translation.load(locale);

  @override
  bool shouldReload(TranslationDelegate old) => false;
}
